name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

flags:
  static_analysis: False   # Fusion + Postgres: evita “hydrate schema”

models:
  jaffle_shop:
    staging:
      +materialized: view
      stripe:
        +materialized: table
    marts:
      +materialized: table
    